"""Report writer for onboarding/offboarding checklists.

Generates two outputs from the task list:
1. checklist.md — a markdown file with checkboxes, ready to paste into Notion/Confluence/email
2. tasks.csv — a structured CSV for ticket tracking or spreadsheet import
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, List


def write_outputs(
    name: str,
    role: str,
    action: str,
    tasks: List[Dict[str, str]],
    output_dir: str,
) -> None:
    """Write checklist.md and tasks.csv to the output directory.

    Args:
        name: employee name
        role: employee role/title
        action: "onboard" or "offboard" — used in headings and filenames
        tasks: list of task dicts from checklist.py
        output_dir: directory to write outputs into (created if needed)
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    action_label = "Onboarding" if action == "onboard" else "Offboarding"

    # --- checklist.md ---
    # Markdown with checkboxes so this can be pasted directly into Notion,
    # Confluence, a GitHub issue, or an email thread
    md_path = out_dir / "checklist.md"
    lines = [
        f"# IT {action_label} Checklist — {name}",
        f"**Role:** {role}",
        "",
        "## Tasks",
        "",
    ]

    for task in tasks:
        # [ ] checkbox format works in GitHub, Notion, Obsidian, and most markdown renderers
        lines.append(f"- [ ] **{task['system']}** — {task['task']} *(Owner: {task['owner']})*")

    lines.extend([
        "",
        "---",
        f"*Generated by IT Onboarding/Offboarding Checklist Automation*",
        f"*github.com/FCDevelopments/it-onboarding-checklist-automation*",
    ])

    md_path.write_text("\n".join(lines), encoding="utf-8")

    # --- tasks.csv ---
    # Structured format for importing into a ticketing system or tracking spreadsheet
    csv_path = out_dir / "tasks.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["employee", "role", "action", "system", "task", "owner", "status"]
        )
        writer.writeheader()
        for task in tasks:
            writer.writerow({
                "employee": name,
                "role": role,
                "action": action_label,
                "system": task["system"],
                "task": task["task"],
                "owner": task["owner"],
                "status": "pending",  # default status — update as tasks are completed
            })
